---
title: "Guide d'utilisation de la tablette"
---

## Connexion

L'application nécessite la création d'utilisateur pour enregistrer les données.
Un utilisateur a été créé par projet.
À l'ouverture de l'application, choisissez l'utilisateur relié au projet (pao).
Le mot de passe est "134679".


## Enregistrer les données

Pour enregistrer les données dans l'application, allez dans l'onglet **"My Projects"**.
Vous devrez normalement voir le projet **"Pointes-Aux-Outardes"** avec un résumé du nombre d'enregistrements effectués.
Cliquez sur l'onglet.
Vous tomberez ensuite sur un menu avec plusieurs onglets.
Choisissez **"Collect Data"**.

Vous verrez alors deux onglets: **stations** et **réplicats**.
L'onglet **stations** contient les informations sur la station (qui enregistre les données, le site, distance de la recharge, distance de la rive, identifiant unique de la station).
L'onglet **réplicats** contient sur les informations sur l'échantillonnage du réplicat relié à la station (# du réplicat, date, latitude/longitude + toutes autres données récoltées pour le réplicat).
Le but d'avoir deux onglets est de ne pas répéter l'information sur la station pour les cinq réplicats.


### Stations

Après avoir cliquer sur **"stations"**, cliquez sur **"Create New Record"** et complétez le formulaire pour la station dont vous enregistrez les données.
Le premier champ correspond à une numérotation automatique de l'enregistrement fait pas l'application (incrémentation de 1 jsuqu'au nombre de stations).
Vous remarquerez au bas du formulaire que le champ "Identifiant unique de la station" s'est rempli automatiquement avec le nom du site, la distance à la recharge et la distance à la rive.
Vous n'avez pas à y toucher.
Dans le champ "Complete?", veuillez choisir "Complete" si vous avez terminé de remplir cette section.

Pour remplir les cinq réplicats associés à la station, cliquez sur l'onglet **"Show More Save Options"** et ensuite sur **"Save & Go to Next Form"**.
Vous serez alors redirigés vers le formulaire de réplicats.
Si certains champs sont manquants, un avertissement apparaitra alors sur l'écran. Veullez remplir tous les champs obligatoires.

### Réplicats

Sur le premier encadré du formulaire de réplicats, vous verrez le nom du projet, le formulaire (instrument) sur lequel vous êtes (réplicats), l'identifiant de l'enregistrement (Record: 1, correspond au numéro donné par l'application à la station), le numéro de l'instance (Instance: #1, #2, #3, #4, #5).
une instance est le formulaire répété (réplicats) pour un même numéro d'enregistrement (stations).
Vous devriez normalement avoir 5 "instances" par numéro de d'enregistrement (record) lorsque vous aurez terminé.
Les champs de date, longitude et latitude sont contrôlés pour éviter d'avoir des valeurs erronées (p. ex. date entre 1er et 14 juin).
La latitude et la longitude devrait être en WGS84.
N'indiquer pas le "-" dans la longitude, il sera ajouté automatiquement lors de l'exportation des données.
La couverture de sable et de végétation est balisée entre 0 et 100.
Dans le champ "Complete?", veuillez choisir "Complete" si vous avez terminé de remplir cette section.

Pour ajouter un autre réplicat associé à la même station, cliquez sur **"Show More Save Options"** et ensuite sur **"Save & Add New Instance"**.
Vous serez alors diriger vers un nouveau formulaire de réplicats avec le même numéro d'enregistrement (record) et un nouveau numéro d'instance.
Lorsque vous allez enregistrer les cinq réplicats pour une station, cliquez sur **"Save & Exit Form"**.
Vous êtes alors redirigez sur la page d'accueil des **réplicats**.
Cliquez sur la flèche pour revenir en arrière (haut à gauche) et et recliquez sur **"Collect Data"** pour recommencer avec une nouvelle station.


## Envoyer les données au serveur

Lorsque vous aurez terminé d'enregistrer les données pour une journée, allez sur le menu du projet et cliquez sur **"Send Data to Server"** et ensuite sur **"Begin Send of All Data"**.
Une fenêtre apparaitra vous demandant si l'application peut avoir accès à votre localisation (**Can this app access your location?**).
Cliquez sur oui.
Si on demande **"Do you want to review modified records before uploading them to the server?"**, cliquez sur **"Proceed with sync"**
Lorsque tout est envoyer au serveur, cliquez sur **"Options"** et sur **"Return to project"**.
L'application peut "gelé" à ce moment. Si tous les cercles sont verts et que vous ne pouvez cliquez sur **"Return to project"**, quittez l'application pour y retourner.
Si tous les cercles sont verts, les données auront tout de même été envoyées au serveur.


## Identifiants

Il y a différents identifiants dans les formulaires qui sont créés automatiquement.
Certains ne sont pas visibles dans les formulaires.

1. Identifiant de l'enregistrement: numéro donné par l'application à la station, de 1 jusqu'au nombre de stations.
2. Identifiant du projet (non-visible) = "pao"
3. Projet Année (Identifiant qui regroupe tout l'échantillonnage fait en 2023): "pao-2023"
4. Identifiant unique de la station (pao-site-distance_recharge-distance_rive): par exemple "pao-SiO-Mo-75"
5. Identifiant unique de l'événement (pao-2023-site-distance_recharge-distance_rive-réplicat): par exemple "pao-2023-SiO-Mo-75-1", correspond au réplicat
6. Identifiant unique de l'échantillon de granulo: Identifiant de l'événement + "-granulo"
7. Identifiant unique de l'échantillon de matière organique: Identifiant de l'événement + "-mo"
8. Identifiant unique de l'échantillon de biodiversité: Identifiant de l'événement + "-biodiv"

Un projet regroupe plusieurs "Projet Année", un "Projet Année" regroupe plusieurs stations, une station regroupe 5 événements, il y a un échantillon de chaque type par événement.
